freelance_site/freelance_site/accounts/models.py
from flask_login import UserMixin

from database import db
from models import UploadFile
# noinspection PyUnresolvedReferences
from order_manager.models import Order, ChatMessages

from base64 import b64encode


class User(UserMixin, db.Model):
    __tablename__ = "users"
    __table_args__ = (
        db.CheckConstraint('rate <= 5'),
        db.CheckConstraint('rate > 0'),
    )

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), index=True, unique=True, nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    hashed_password = db.Column(db.String, unique=False, nullable=False)
    avatar_file_id = db.Column(db.Integer, db.ForeignKey('uploadfiles.id'), unique=True)
    balance = db.Column(db.Float, nullable=False, default=0)
    info = db.Column(db.String(1000))
    rate = db.Column(db.Float)

    my_orders = db.relationship('Order', backref='customer', lazy='dynamic', foreign_keys='Order.customer_id')
    accepted_orders = db.relationship('Order', backref='executor', lazy='dynamic',
                                      foreign_keys='Order.executor_id')
    messages = db.relationship('ChatMessages', backref='user', lazy='dynamic')

    def get_avatar(self):
        return b64encode(UploadFile.query.get(self.avatar_file_id).data).decode("utf-8")

    def __repr__(self):
        return f"<User {self.username}>"

freelance_site/freelance_site/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Email


class RegisterForm(FlaskForm):
    username = StringField('Имя пользователя: ', validators=[DataRequired(message='Поле обязательно')])
    email = StringField('Почта: ',
                        validators=[DataRequired(message='Поле обязательно'), Email(message='Почта некорректна')])
    password = PasswordField('Пароль: ', validators=[DataRequired(message='Поле обязательно')])
    repeat_password = PasswordField('Повторите пароль: ', validators=[DataRequired(message='Поле обязательно')])
    submit = SubmitField("Зарегистрироваться")


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя: ', validators=[DataRequired(message='Поле обязатльно')])
    password = PasswordField('Пароль: ', validators=[DataRequired(message='Поле обязательно')])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

freelance_site/freelance_site/accounts/controllers.py
import json

from flask import request, redirect, url_for, flash, render_template, Blueprint, jsonify
from flask_login import login_user, login_required, logout_user, current_user

from accounts.forms import RegisterForm, LoginForm
from accounts.services import find_user_by_username_and_password, add_new_user_to_database, find_user_by_username, \
    find_user_by_email, change_current_user_email
from accounts.send_message_confirm_email import verify_mail_token_new_user, send_link_confirm_email, \
    verify_mail_token_current_user

accounts_blueprint = Blueprint('accounts', __name__, template_folder='templates')


@accounts_blueprint.route('/verify_email_new_user/<token>', methods=['GET'])
def verify_email_new_user(token):
    if current_user.is_authenticated:
        return redirect(url_for('welcome.main_page'))
    username, email, password = verify_mail_token_new_user(token)
    if find_user_by_username(username):
        print('Почта уже подтверждена')
    else:
        add_new_user_to_database(username, email, password)
    return redirect(url_for('welcome.main_page'))


@accounts_blueprint.route('/verify_email_current_user/<token>', methods=('GET', 'POST'))
def verify_email_current_user(token):
    email = verify_mail_token_current_user(token)
    change_current_user_email(email)
    return 'Ваша почта успешно подтверждена'


@accounts_blueprint.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        repeat_password = form.repeat_password.data
        if password != repeat_password:
            print('Пароли не совпадают')
            return redirect(url_for('accounts.register'))
        if find_user_by_email(email):
            print('Пользователь с такой почтой уже существует')
            return redirect(url_for('accounts.register'))
        if find_user_by_username(username):
            print('Пользователь с таким логином уже существует')
            return redirect(url_for('accounts.register'))
        else:
            send_link_confirm_email(username, email, password)
            print('Вам на почту было отправлено сообщение с подтверждением')
            return redirect(url_for('welcome.main_page'))

    return render_template('accounts/register.html', form=form)


@accounts_blueprint.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember_me = form.remember_me.data
        try:
            user = find_user_by_username_and_password(username, password)
        except:
            return json.dumps({'success': 'false', 'msg': 'Пользователя с таким логином или паролем не существует'})
        else:
            login_user(user, remember=remember_me)
            return json.dumps({'success': 'true', 'msg': 'Вы успешно вошли'})
    return render_template('accounts/login.html', form=form)


@accounts_blueprint.route("/logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('welcome.main_page'))

freelance_site/freelance_site/accounts/templates/accounts/confirm_email_current_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<h1>Подтсверждение электронной почты для {{ username }}</h1>
Перейдите по ссылке для подтверждения электронной
почты: {{ url_for('accounts.verify_email_current_user', token=token, _external=True) }}
</body>
</html>

freelance_site/freelance_site/accounts/templates/accounts/confirm_email_new_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<h1>Подтсверждение электронной почты для {{ username }}</h1>
Перейдите по ссылке для подтверждения электронной
почты: {{ url_for('accounts.verify_email', token=token, _external=True) }}
</body>
</html>

freelance_site/freelance_site/accounts/templates/accounts/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Восстановление пароля</title>

    <!-- Custom fonts for this template-->
    <link href="../../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../../../static/css/main.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Забыли свой пароль?</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Введите почту">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Перезаписать пароль
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Создать аккаунт</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Уже есть аккаунт?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="../../../static/vendor/jquery/jquery.min.js"></script>
    <script src="../../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="../../../static/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="../../../static/js/sb-admin-2.min.js"></script>

</body>

</html>

freelance_site/freelance_site/accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Вход</title>

    <!-- Custom fonts for this template-->

    <link href="../../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../../../static/css/main.min.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="../../../static/js/login.js"></script>

</head>

<body class="bg-gradient-primary">

<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Добро пожаловать!</h1>
                                </div>
                                <form class="user" id='form1' method="post">
                                    {{ form.csrf_token() }}
                                    <div id="warning"></div>
                                    <div class="form-group">
                                        {{ form.username(class="form-control form-control-user", placeholder="Логин") }}
                                    </div>
                                    <div class="form-group">
                                        {{ form.password(class="form-control form-control-user", placeholder="Пароль") }}
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox small">
                                            {{ form.remember_me(class="custom-control-input") }}
                                            {{ form.remember_me.label(class="custom-control-label") }}
                                        </div>
                                    </div>
                                    {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                                    <hr>
                                    <a href="../../../welcome/templates/welcome/main_page.html"
                                       class="btn btn-google btn-user btn-block">
                                        <i class="fab fa-google fa-fw"></i> Войти с Google
                                    </a>
                                    <a href="../../../welcome/templates/welcome/main_page.html"
                                       class="btn btn-facebook btn-user btn-block">
                                        <i class="fab fa-facebook-f fa-fw"></i> Войти с Facebook
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="forgot-password.html">Забыли пароль?</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{{ url_for('accounts.register') }}">Создать аккаунт</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
<!-- Bootstrap core JavaScript-->
<script src="../../../static/vendor/jquery/jquery.min.js"></script>
<script src="../../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="../../../static/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="../../../static/js/sb-admin-2.min.js"></script>

</body>

</html>

freelance_site/freelance_site/accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Регистрация</title>

    <!-- Custom fonts for this template-->
    <link href="../../../static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="../../../static/css/main.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Создание аккаунта</h1>
                        </div>
                        <form class="user" method="post">
                            {{ form.csrf_token() }}
                            <div class="form-group">
                                {{ form.username(class="form-control form-control-user", placeholder="Логин") }}
                            </div>
                            <div class="form-group">
                                {{ form.email(class="form-control form-control-user", placeholder="Почта") }}
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    {{ form.password(class="form-control form-control-user", placeholder="Пароль") }}
                                </div>
                                <div class="col-sm-6">
                                    {{ form.repeat_password(class="form-control form-control-user", placeholder="Повторите пароль") }}
                                </div>
                            </div>
                            {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                            <hr>
                            <a href="../../../welcome/templates/welcome/main_page.html"
                               class="btn btn-google btn-user btn-block">
                                <i class="fab fa-google fa-fw"></i> Зарегистрироваться с Google
                            </a>
                            <a href="../../../welcome/templates/welcome/main_page.html"
                               class="btn btn-facebook btn-user btn-block">
                                <i class="fab fa-facebook-f fa-fw"></i> Зарегистрироваться с Facebook
                            </a>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="forgot-password.html">Забыли пароль?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{{ url_for('accounts.login') }}">У вас уже есть аккаунт?</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="../../../static/vendor/jquery/jquery.min.js"></script>
<script src="../../../static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="../../../static/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="../../../static/js/sb-admin-2.min.js"></script>

</body>

</html>