freelance_site/freelance_site/order_manager/controllers.py
from flask import redirect, url_for, render_template, Blueprint
from flask_login import current_user
from werkzeug.security import check_password_hash

from accounts.send_message_confirm_email import send_link_change_email
from accounts.services import change_current_user_password, change_current_user_avatar, change_current_user_describe, \
    add_current_user_to_order_executor, get_user_by_id, increase_current_user_balance, find_user_by_username, \
    change_current_user_login, find_user_by_email, complete_order
from local_configs import Configuration
from order_manager.forms import PostOrderForm, BalanceForm, ChangePasswordForm, ChangeLoginForm, ChangeEmailForm, \
    ChangeUserAvatarForm, ChangeDescriptionForm, TakeOrderForm, CompleteOrderForm, OrderAcceptanceForm
from order_manager.services import get_all_specializationtypes, get_all_order_types, \
    get_published_orders_by_specialization, \
    get_order_by_id, get_my_orders_by_status, get_my_accepted_orders_by_id, add_new_order_to_database, \
    add_solution_file_and_put_on_check

order_manager_blueprint = Blueprint('order_manager', __name__, template_folder='templates')


@order_manager_blueprint.route('/', methods=('GET', 'POST'))
def main_page():
    return redirect(url_for('order_manager.all_orders'))


@order_manager_blueprint.route('/order_work', methods=('GET', 'POST'))
def order_work():
    form = PostOrderForm()
    if form.validate_on_submit():
        order_name = form.name.data
        order_spec_id = form.specialization.data
        order_type_id = form.type.data
        file = form.file.data
        deadline = form.deadline.data
        description = form.description.data
        try:
            price = int(form.price.data)
        except:
            print('Введена некорректная цена')
            return redirect(url_for('order_manager.order_work'))
        else:
            if current_user.balance >= price:
                add_new_order_to_database(order_name, order_spec_id, order_type_id, file, deadline, description, price)
                print('Заказ успешно добавлен')
                return redirect(url_for('order_manager.all_orders'))
            else:
                print('У вас недостаточно денег')
                return redirect(url_for('order_manager.order_work'))

    return render_template('order_manager/post_work.html', specializationtypes=get_all_specializationtypes(),
                           types=get_all_order_types(), form=form)


@order_manager_blueprint.route('/balance', methods=('GET', 'POST'))
def balance():
    form = BalanceForm()
    if form.validate_on_submit():
        try:
            sum_of_money = float(form.refill.data)
        except:
            print('==========Введена некорректная сумма==========')
            return redirect(url_for('order_manager.balance'))
        else:
            print('==========Счет успешно пополнен==========')
            increase_current_user_balance(sum_of_money)
            return redirect(url_for('order_manager.balance'))
    return render_template('order_manager/balance.html', specializationtypes=get_all_specializationtypes(), form=form)


@order_manager_blueprint.route('/all_orders', methods=('GET', 'POST'))
@order_manager_blueprint.route('/all_orders/<int:spec_id>/<int:page>', methods=('GET', 'POST'))
def all_orders(spec_id=0, page=1):
    orders = get_published_orders_by_specialization(spec_id=spec_id).paginate(page, Configuration.POSTS_PER_PAGE, False)
    return render_template('order_manager/all_orders.html', orders=orders, cur_page=page,
                           count=len(get_published_orders_by_specialization(
                               spec_id=spec_id).all()) // Configuration.POSTS_PER_PAGE,
                           specializationtypes=get_all_specializationtypes(), current_spec_id=spec_id)


@order_manager_blueprint.route("/order_page/<int:order_id>", methods=("GET", "POST"))
def order_page(order_id: int):
    take_order_form = TakeOrderForm()
    complete_order_form = CompleteOrderForm()
    order_acceptance_form = OrderAcceptanceForm()
    if complete_order_form.validate_on_submit() and complete_order_form.solution_file.data:
        solution_file = complete_order_form.solution_file.data
        add_solution_file_and_put_on_check(solution_file, order_id)
        print('Заказ перешел в стадию проверки')
        return redirect(url_for('order_manager.order_page', order_id=order_id))
    elif take_order_form.validate_on_submit() and take_order_form.submit_take_order.data:
        add_current_user_to_order_executor(order_id)
        print('Заказ принят')
        return redirect(url_for('order_manager.order_page', order_id=order_id))
    elif order_acceptance_form.validate_on_submit() and order_acceptance_form.submit_accept_order.data:
        complete_order(order_id)
        return redirect(url_for('order_manager.order_page', order_id=order_id))
    try:
        order = get_order_by_id(id=order_id)
        customer = get_user_by_id(user_id=order.customer_id)
        executor = get_user_by_id(user_id=order.executor_id)
        return render_template('order_manager/order_page.html', order=order, customer=customer, executor=executor,
                               specializationtypes=get_all_specializationtypes(), take_order_form=take_order_form,
                               complete_order_form=complete_order_form, order_acceptance_form=order_acceptance_form)
    except:
        return redirect(url_for('order_manager.all_orders'))


@order_manager_blueprint.route('/profile', methods=('GET', 'POST'))
def profile():
    form = ChangeDescriptionForm()
    if form.validate_on_submit():
        info_about_user = form.description.data
        change_current_user_describe(info_about_user)
        return redirect(url_for('order_manager.profile'))

    return render_template('order_manager/profile.html', specializationtypes=get_all_specializationtypes(), form=form)


@order_manager_blueprint.route("/user/<int:user_id>", methods=["GET"])
def user_profile(user_id: int):
    try:
        user = get_user_by_id(user_id=user_id)
        return render_template('order_manager/user_profile.html', user=user,
                               specializationtypes=get_all_specializationtypes())
    except:
        return redirect(url_for('order_manager.all_orders'))


@order_manager_blueprint.route('/profile/change_description', methods=('GET', 'POST'))
def profile_change_description():
    form = ChangeDescriptionForm()
    if form.validate_on_submit():
        info_about_user = form.description.data
        change_current_user_describe(info_about_user)
        return redirect(url_for('order_manager.profile'))

    return render_template('order_manager/profile_change_description.html',
                           specializationtypes=get_all_specializationtypes(), form=form)


@order_manager_blueprint.route('/my_orders', methods=('GET', 'POST'))
@order_manager_blueprint.route('/my_orders/<string:status>/<int:page>', methods=('GET', 'POST'))
def my_orders(status='Опубликовано', page=1):
    orders = get_my_orders_by_status(status=status).paginate(page, Configuration.POSTS_PER_PAGE, False)
    return render_template('order_manager/my_orders.html', orders=orders, cur_page=page,
                           count=len(get_my_orders_by_status(status=status).all()) // Configuration.POSTS_PER_PAGE,
                           status=status,
                           specializationtypes=get_all_specializationtypes())


@order_manager_blueprint.route('/taken_orders', methods=('GET', 'POST'))
@order_manager_blueprint.route('/taken_orders/<string:status>/<int:page>', methods=('GET', 'POST'))
def taken_orders(status='На выполнении', page=1):
    orders = get_my_accepted_orders_by_id(status=status).paginate(page, Configuration.POSTS_PER_PAGE, False)
    return render_template('order_manager/taken_orders.html', orders=orders, cur_page=page,
                           count=len(get_my_accepted_orders_by_id(status=status).all()) // Configuration.POSTS_PER_PAGE,
                           status=status,
                           specializationtypes=get_all_specializationtypes())


@order_manager_blueprint.route('/preferences', methods=('GET', 'POST'))
def preferences():
    form = ChangeUserAvatarForm()
    if form.validate_on_submit():
        file = form.avatar.data
        print(type(file))
        if file.content_type in ('image/jpeg', 'image/png', 'image/svg+xml'):
            change_current_user_avatar(file)
            print('Фото профиля успешно изменено')
            return redirect(url_for('order_manager.preferences'))
        else:
            print('Некорректный тип файла')
            return redirect(url_for('order_manager.preferences'))

    return render_template('order_manager/preferences.html', specializationtypes=get_all_specializationtypes(),
                           form=form)


@order_manager_blueprint.route('/preferences/change_email', methods=('GET', 'POST'))
def change_email():
    form = ChangeEmailForm()
    if form.validate_on_submit():
        new_email = form.email.data
        if find_user_by_email(new_email):
            print(find_user_by_email(new_email))
            print('Данная почта уже занята')
            return redirect(url_for('order_manager.change_email'))
        send_link_change_email(new_email)
        print('Вам на почту было отправлено сообщение с подтверждением')
        return redirect(url_for('order_manager.preferences'))
    return render_template('order_manager/change_email.html', specializationtypes=get_all_specializationtypes(),
                           form=form)


@order_manager_blueprint.route('/preferences/change_login', methods=('GET', 'POST'))
def change_login():
    form = ChangeLoginForm()
    if form.validate_on_submit():
        new_username = form.username.data
        if find_user_by_username(new_username):
            print('Данный логин уже занят')
            return redirect(url_for('order_manager.change_login'))

freelance_site/freelance_site/order_manager/templates/order_manager/all_orders.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>Orders</title>
{% endblock %}
{% block content %}
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Заказы в поиске исполнителя</h1>
    </div>
    <div class="card">
        <div class="card-body">
            {% for order in orders.items %}
                <h4 class="card-title">{{ order.name }}</h4>
                <h6 class="card-text">Заказчик: <a
                        href="{{ url_for('order_manager.user_profile', user_id=order.customer_id) }}">{{ order.customer.username }}</a>
                </h6>
                <p class="card-text">Описание заказа:</p>
                <p class="card-text">Цена: {{ order.price }} рублей</p>
                <a href="{{ url_for('order_manager.order_page', order_id=order.id) }}"
                   class="btn btn-primary">Перейти</a>
                <hr>
            {% endfor %}
        </div>
    </div>
    <!-- Пагинация -->
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item">
                {% if orders.has_prev %}
                    <a class="page-link"
                       href="{{ url_for('order_manager.all_orders', spec_id=current_spec_id, page = orders.prev_num) }}">Назад</a>
                {% else %}
                    <a class="page-link" aria-disabled="true">Назад</a>
                {% endif %}
            </li>
            {% for i in range(1, count + 1) %}
                {% if i != cur_page %}
                    <li class="page-item">
                        <a href="{{ url_for('order_manager.all_orders', spec_id=current_spec_id, page = i) }}"
                           class="page-link">{{ i }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="page-item">
                {% if orders.has_next %}
                    <a class="page-link"
                       href="{{ url_for('order_manager.all_orders', spec_id=current_spec_id, page = orders.next_num) }}">Вперед</a>
                {% else %}
                    <a class="page-link" aria-disabled="true">Вперед</a>
                {% endif %}
            </li>

        </ul>
    </nav>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/balance.html
{% extends 'order_manager/base.html' %}

{% block header %}
    <title>Баланс</title>
{% endblock %}

{% block content %}
    <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-12 d-none"></div>
                        <div class="col-lg-12">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Пополнение счета</h1>
                                </div>
                                <form class="user" method="post" enctype="multipart/form-data">
                                    {{ form.csrf_token() }}
                                    <!-- Название работы -->
                                    <div class="form-group">
                                        {{ form.refill.label() }}
                                        {{ form.refill(class="form-control-user") }}
                                        {{ form.submit(class="btn btn-primary btn-user") }}
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/change_email.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>Изменение почты</title>
{% endblock %}
{% block content %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-12 d-none"></div>
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Изменение почты</h1>
                                    </div>
                                    <form class="user" method="post">
                                        {{ form.csrf_token }}
                                        <div class="form-group">
                                            {{ form.email(class="form-control form-control-user", placeholder="Введите новую почту") }}
                                        </div>
                                        {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                                    </form>
                                    <br>
                                    <a class="nav-link" href="{{ url_for('order_manager.preferences') }}">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/change_login.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>Изменение логина</title>
{% endblock %}
{% block content %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-12 d-none"></div>
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Изменение логина</h1>
                                    </div>
                                    <form class="user" method="post">
                                        {{ form.csrf_token }}
                                        <div class="form-group">
                                            {{ form.username(class="form-control form-control-user", placeholder="Введите новый логин") }}
                                        </div>
                                        {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                                    </form>
                                    <br>
                                    <a class="nav-link" href="{{ url_for('order_manager.preferences') }}">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/change_password.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>ChangePassword</title>
{% endblock %}
{% block content %}
    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-12 d-none"></div>
                            <div class="col-lg-12">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Изменение пароля</h1>
                                    </div>
                                    <form class="user" method="post">
                                        {{ form.csrf_token }}
                                        <div class="form-group">
                                            {{ form.password(class="form-control form-control-user", placeholder="Введите ваш пароль") }}
                                        </div>
                                        <div class="form-group">
                                            {{ form.new_password(class="form-control form-control-user", placeholder="Введите ваш новый пароль") }}
                                        </div>
                                        <div class="form-group">
                                            {{ form.rep_new_password(class="form-control form-control-user", placeholder="Повторите ваш новый пароль") }}
                                        </div>
                                        {{ form.submit(class="btn btn-primary btn-user btn-block") }}
                                    </form>
                                    <br>
                                    <a class="nav-link" href="{{ url_for('order_manager.preferences') }}">Назад</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/order_page.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>Order #{{ order.id }}</title>
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Order #{{ order.id }}</h1>
        <h2 class="h4 text-gray-900 mb-4">{{ order.name }}</h2>
        <p class="h4 text-gray-900 mb-4">{{ order.description }}</p>
        <p class="h4 text-gray-900 mb-4">Срок: {{ order.deadline }}</p>
        <p class="h4 text-gray-900 mb-4">Статус: {{ order.status }}</p>
        <p class="h4 text-gray-900 mb-4">Цена: {{ order.price }}</p>
        <h6 class="h4 text-gray-900 mb-4">Дополнительный файл:
            {% if order.additional_file_id != None %}
                <a href="data:image/png;base64,{{ order.get_file() }}">Скачать файл</a>
            {% else %}
                Отсутствует
            {% endif %}
        </h6>
        {% if order.customer_id != current_user.id %}
            <p class="h4 text-gray-900 mb-4">Заказчик:
                {% if customer.avatar_file_id != None %}
                    <img width="70" height="70" src="{{ customer.get_avatar() }}" alt="avatar">
                {% else %}
                    <img width="70" height="70" src="../../../static/img/undraw_profile.svg"
                         alt="avatar">
                {% endif %}
                <a href="{{ url_for('order_manager.user_profile', user_id=customer.id) }}">{{ customer.username }}</a>
            </p>
            <br>
            {% if order.status == 'Опубликовано' %}
                <form method="post">
                    {{ take_order_form.csrf_token }}
                    {{ take_order_form.offer(cols="100", rows="10") }}
                    <br>
                    {{ take_order_form.submit_take_order(class="btn btn-primary btn-user") }}
                </form>
            {% elif order.status == 'На выполнении' %}
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {{ complete_order_form.csrf_token }}
                    <div class="form-file form-control-user">
                        {{ complete_order_form.solution_file.label(class="form-file-text") }}
                        {{ complete_order_form.solution_file(class="form-file-input") }}
                        {{ complete_order_form.submit(class="btn btn-primary btn-user") }}
                    </div>
                </form>
            {% elif order.status == 'На проверке' %}
                <h1>Заказ на проверке</h1>
            {% endif %}
        {% elif order.customer_id == current_user.id %}
            <p class="h4 text-gray-900 mb-4">Исполнитель:
                {% if executor.avatar_file_id != None %}
                    <img width="70" height="70" src="{{ executor.get_avatar() }}" alt="avatar">
                {% else %}
                    <img width="70" height="70" src="../../../static/img/undraw_profile.svg"
                         alt="avatar">
                {% endif %}
                <a href="{{ url_for('order_manager.user_profile', user_id=executor.id) }}">{{ executor.username }}</a>
            </p>
            {% if order.status == 'На проверке' %}
                <hr>
                <h6 class="h4 text-gray-900 mb-4">Файл с решением:
                    <a href="data:image/png;base64,{{ order.get_solution_file() }}">Скачать файл</a>
                </h6>
                <form method="post">
                    {{ order_acceptance_form.csrf_token }}
                    {{ order_acceptance_form.submit_accept_order(class="btn btn-primary btn-user") }}
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/profile.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>MyProfile</title>
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Мой профиль</h1>
        <h4 class="">
            {% if current_user.avatar_file_id != None %}
                <img width="70" height="70" src="data:image/png;base64,{{ current_user.get_avatar() }}"
                     alt="avatar">
            {% else %}
                <img width="70" height="70" src="../../../static/img/undraw_profile.svg"
                     alt="avatar">
            {% endif %}
            <a href="">{{ current_user.username }}</a></h4>
        <h1 class="h4 text-gray-900 mb-4">Рейтинг: 4.25</h1>
    </div>
    <hr>
    <!-- Информация о пользователе -->
    {% if current_user.info == None %}
        <form method="post">
            {{ form.csrf_token }}
            <div class="text-center">
                {{ form.description(cols="100", rows="10", placeholder="Добавьте информацию о себе") }}
                <br>
                {{ form.submit(class="btn btn-primary btn-user") }}
            </div>
        </form>
    {% else %}
        <div class="text-center">
            <h2>{{ current_user.info }}</h2>
            <a href="{{ url_for('order_manager.profile_change_description') }}">
                <button type="submit" class="btn btn-primary btn-user">Изменить описание
                </button>
            </a>
        </div>

    {% endif %}
    <br>
    <!--Отзывы-->
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Отзывы</h1>
    </div>
    <div class="card">
        <div class="card-body">
            <h5 class="card-text">
                {% if current_user.avatar_file_id != None %}
                    <img width="50" height="50" src="data:image/png;base64,{{ current_user.get_avatar() }}">
                {% else %}
                    <img width="50" height="50" src="../../../static/img/undraw_profile.svg">
                {% endif %}
                <a href="">{{ current_user.username }}</a></h5>
            <p class="card-text">Комментарий</p>
            <p class="card-text">Оценка: 4/5</p>
        </div>
    </div>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/profile_change_description.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>ChangeDescription</title>
{% endblock %}

{% block content %}
    <form method="post">
        {{ form.csrf_token }}
        <div class="text-center">
            {{ form.description(cols="100", rows="10", placeholder="Добавьте информацию о себе") }}
            <br>
            {{ form.submit(class="btn btn-primary btn-user") }}
        </div>
    </form>
    <a href="{{ url_for('order_manager.profile') }}">
        <button class="btn btn-primary btn-user">Назад</button>
    </a>
{% endblock %}

freelance_site/freelance_site/order_manager/templates/order_manager/taken_orders.html
{% extends 'order_manager/base.html' %}
{% block header %}
    <title>TakenOrders</title>
{% endblock %}

{% block content %}
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-4">Взятые заказы</h1>
    </div>
    <nav class="nav nav-pills nav-justified">
        {% if status == 'На выполнении' %}
            <a class="nav-link active"
               href="{{ url_for('order_manager.taken_orders', status='На выполнении', page=1) }}">На
                выполнении</a>
            <a class="nav-link"
               href="{{ url_for('order_manager.taken_orders', status='На проверке', page=1) }}">На проверке</a>
            <a class="nav-link"
               href="{{ url_for('order_manager.taken_orders', status='Выполнено', page=1) }}">Выполнено</a>
        {% elif status == 'На проверке' %}
            <a class="nav-link"
               href="{{ url_for('order_manager.taken_orders', status='На выполнении', page=1) }}">На выполнении</a>
            <a class="nav-link active"
               href="{{ url_for('order_manager.taken_orders', status='На проверке', page=1) }}">На проверке</a>
            <a class="nav-link"
               href="{{ url_for('order_manager.taken_orders', status='Выполнено', page=1) }}">Выполнено</a>
        {% else %}
            <a class="nav-link"
               href="{{ url_for('order_manager.taken_orders', status='На выполнении', page=1) }}">На
                выполнении</a>
            <a class="nav-link"
               href="{{ url_for('order_manager.taken_orders', status='На проверке', page=1) }}">На проверке</a>
            <a class="nav-link active" aria-current="page"
               href="{{ url_for('order_manager.taken_orders', status='Выполнено', page=1) }}">Выполнено</a>
        {% endif %}
    </nav>
    <div class="card">
        <div class="card-body">
            {% for order in orders.items %}
                <h4 class="card-title">{{ order.name }}</h4>
                <p class="card-text">Описание заказа:</p>
                <p class="card-text">Статус: {{ order.status }}</p>
                <p class="card-text">Цена: {{ order.price }} рублей</p>
                <a href="{{ url_for('order_manager.order_page', order_id=order.id) }}"
                   class="btn btn-primary">Перейти</a>
                <hr>
            {% endfor %}
        </div>
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            <li class="page-item">
                {% if orders.has_prev %}
                    <a class="page-link"
                       href="{{ url_for('order_manager.taken_orders', status=status, page = orders.prev_num) }}">Назад</a>
                {% else %}
                    <a class="page-link" aria-disabled="true">Назад</a>
                {% endif %}
            </li>
            {% for i in range(1, count + 1) %}
                {% if i != cur_page %}
                    <li class="page-item">
                        <a href="{{ url_for('order_manager.all_orders', status=status, page = i) }}"
                           class="page-link">{{ i }}</a>
                    </li>
                {% else %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="page-item">
                {% if orders.has_next %}
                    <a class="page-link"
                       href="{{ url_for('order_manager.all_orders', status=status, page = orders.next_num) }}">Вперед</a>
                {% else %}
                    <a class="page-link" aria-disabled="true">Вперед</a>
                {% endif %}
            </li>

        </ul>
    </nav>
{% endblock %}